project10/app10/urls.py
from django.urls import path
from . import views

app_name='app10'

urlpatterns=[
    path('',views.index,name='index'),
    path('registration/',views.registration,name='registration'),
    path('login/',views.login1,name='login'),
    path('home/<int:id>',views.home,name='home'),
    path('update/<int:id>',views.update,name='update'),
    path('delete/<int:id>',views.delete,name='delete'),
    path('changepassword/<int:id>',views.changepassword,name='changepassword'),
    path('logout/',views.logout,name='logout'),
    path('gallery/',views.gallery,name='gallery'),
    path('details/<int:id>',views.details,name='details'),
]

project10/project10/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app10.urls'))
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

project10/app10/models.py
from django.db import models

# Create your models here.
class login(models.Model):
    Name=models.CharField(max_length=10)
    Age=models.IntegerField()
    Place=models.CharField(max_length=10)
    Photo=models.ImageField(upload_to='media/',null=True,blank=True)
    Email=models.EmailField()
    Password=models.CharField(max_length=10)

class Gallery(models.Model): 
   Brand=models.CharField(max_length=10)
   Name=models.CharField(max_length=10)
   Photo=models.ImageField(upload_to='media/',null=True,blank=True)
   Price=models.IntegerField()

project10/app10/views.py
from builtins import id
from django.shortcuts import render,redirect
from django.contrib import messages
from .form import registerform, loginform, updateform,changepasswordform
from .models import login,Gallery
from django.contrib.auth import logout as logouts
from django.conf import settings
from django.core.mail import send_mail


# Create your views here.
def index(request):
    return render(request,'index.html')
def registration(request):
    if request.method=='POST':
        form=registerform(request.POST)
        if form.is_valid():
            name=form.cleaned_data['Name']
            age=form.cleaned_data['Age']
            photo=form.cleaned_data['Photo']
            place=form.cleaned_data['Place']
            email=form.cleaned_data['Email']
            password=form.cleaned_data['Password']
            confirmpassword=form.cleaned_data['confirmpassword']

            user=login.objects.filter(Email=email).exists()
            if user:
                messages.warning(request,'Email Alredy exist')
                return redirect('/login/')
            elif password!=confirmpassword:
                messages.warning(request,'Password Mismatch')
            else:
                tab=login(Name=name,Age=age,Place=place,Email=email,Photo=photo,Password=password)
                tab.save()


                subject = 'welcome to qqqqq'
                message = f'Hi {name}, thank you for registering in gfdgdfgdfs.'
                email_from = settings.EMAIL_HOST_USER
                recipient_list = [email, ]
                send_mail( subject, message, email_from, recipient_list )


                messages.success(request,'DATA SAVED')
                return redirect('/')
    else:
        form=registerform() 
    return render(request,'registration.html',{'form':form})
    
def login1(request):
    if request.method=='POST':
        form=loginform(request.POST)
        if form.is_valid():
            email=form.cleaned_data['Email']
            password=form.cleaned_data['Password']
            try:
                user=login.objects.get(Email=email)
                if not user:
                    messages.warning(request,'Email does not exist')
                    return redirect('/login/')
                elif password!=user.Password:
                    messages.warning(request,'Password Incorrect')
                    return redirect('/login/')
                else:
                    messages.success(request,'Success')
                    return redirect('/home/%s' % user.id)
            except:
                messages.warning(request,'Email or Password incorrect')
                return redirect('/login/')
    else:
        form=loginform()
    return render(request,'login.html',{'form':form})
def home(request,id):
        user=login.objects.get(id=id)
        return render(request,'home.html',{'user':user})

def update(request,id):
    user=login.objects.get(id=id)
    if request.method=='POST':
        form=updateform(request.POST or None,instance=user)
        if form.is_valid():
            form.save()
            messages.success(request,'Success')
            return redirect('/home/%s' % user.id)
    else:
        form=updateform(instance=user)
    return render(request,'update.html',{'user':user,'form':form})

def delete(request):
    user=login.objects.get(id=id)
    user.delete()
    messages.success(request,'SUCCESS')
    return redirect('/')

def logout(request):
    logouts(request)
    messages.success(request,'SUCCESS')
    return redirect('/')

def changepassword(request,id):
    user=login.objects.get(id=id)
    if request.method=='POST':
        form=changepasswordform(request.POST or None)
        if form.is_valid():
            oldpassword=form.cleaned_data['OldPassword']
            newpassword=form.cleaned_data['NewPassword']
            confirmpassword=form.cleaned_data['ConfirmPassword']

            if oldpassword!= user.Password:
                messages.warning(request,"incorrect")
                return redirect('/changepassword/%s' % user.id)
            elif oldpassword==newpassword: 
                messages.warning(request, "password similar")
                return redirect('/changepassword/%s' % user.id)
            elif newpassword!=confirmpassword:
                messages.warning(request,"password new")
                return redirect('/changepassword/%s'% user.id)
            else:
                user.Password=newpassword
                user.save()
                messages.success(request,"change success")
    else:
        form=changepasswordform()
        return render(request,'changepassword.html',{'user':user, 'form':form})

def logout(request):
    logouts(request)
    messages.success(request,"logged out")
    return redirect('/')

def gallery(request):
    images=Gallery.objects.all()
    return render(request,'gallery.html',{'images':images})

def details(request, id): 
    images=Gallery.objects.get(id=id)
    return render(request,'details.html',{'images':images}) 

project10/app10/templates/changepassword.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for m in messages %}
    {{m}}
    {% endfor %}
    <form action="" method="post">
        {% csrf_token %}
        <table>
            <tr>
                {{form.as_table}}
            </tr>
        </table>
        <input type="submit" value="changepassword">
    </form>
</body>
</html>

project10/app10/templates/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {{images.id}}
    {{images.Brand}}
    {{images.Name}}
    {{images.Price}}
    
    <img style="width:200px;height:100px;" src="{{images.Photo.url}}">
    
    </body>
</html>

project10/app10/templates/gallery.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
   

  <table>
    <tr>
        <th>Name</th>
        <th>Photo</th>
        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
    </tr>
    {% for img in images %}
    <tr>
        <td>{{img.Name}}</td>
        <td><a href="{% url 'app10:details' img.id %}"><img src="{{ img.Photo.url }}" height="100px" width="200px"></a></td>
        
    </tr>
    {% endfor %}</td>
    </tr>
</table

project10/app10/templates/home.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for m in messages %}
    {{m}}
    {% endfor %}
    {{user.id}}
    {{user.name}}
    <a href="{% url 'app10:update' user.id %}">Update</a>
    <a href="{% url 'app10:delete' user.id %}">Delete</a>
    <a href="{% url 'app10:logout' %}">logout</a>

   
</body>
</html>

project10/app10/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel ="stylesheet" href ="{% static 'css/style.css' %}">
</head>
<body>
    <h1>project 0000</h1>
    <p1></p1>
    <a href ="{% url 'app10:login' %}">login</a>
    <a href ="{% url 'app10:gallery' %}">gallery</a>
</body>
</html>

project10/app10/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for m in messages %}
    {{m}}
    {% endfor %}
    <form action="" method="post" >
        {% csrf_token %}
        <table>
            <tr>{{form.as_table}} </tr>
        </table>            
        <input type="submit" value="Login">
    </form>
    <a href="{% url 'app10:registration' %}">Create account</a>
</body>
</html>

project10/app10/templates/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for m in messages %}
    {{m}}
    {% endfor %}
    <form action="" method="post">
        {% csrf_token %}
        <table>
            <tr>{{form.as_table}}</tr>
        </table>
        <input type="submit" value="submit">
       
    </form>
      
</body>
</html>

project10/app10/templates/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for m in messages %}
    {{m}}
    {% endfor %}
    
    <form action="" method="post">
        {% csrf_token %}
        <table>
            <tr>{{form.as_table}}</tr>
        </table>
        <input type="submit" value="update">
       
    </form>
      
</body>
</html>